# -*- coding: utf-8 -*-
"""WEB-AB-TEST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TkW-bYwnaL5zhBoOzdHYNxJqJMRBXnhv
"""

import numpy as np
import pandas as pd
import itertools
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.stats.api as sms
from scipy.stats import ttest_1samp, shapiro, levene, ttest_ind, mannwhitneyu, pearsonr, spearmanr, kendalltau, \
    f_oneway, kruskal
from statsmodels.stats.proportion import proportions_ztest
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("websitetest.csv")
df.head()

df.shape

"""Sayfayı birden fazla ziyaret eden kullanıcılar için ziyaret başına 1 işaretliyoruz."""

df = df.groupby(["IP Address", "LoggedInFlag", "ServerID"])["VisitPageFlag"].sum()

df = df.reset_index(name="VisitPageFlagSum")
df.head()

df["VisitPageFlag"] = df["VisitPageFlagSum"].apply(lambda x: 1 if x != 0 else 0)
df.head()

"""Daha sonra veri kümesini Test ve Kontrol gruplarına ayırmam gerekiyor. Bu işlemi ServerID yardımıyla gerçekleştireceğim. ServerID 1'i Test grubu, ServerID 2 ve 3'ü ise Kontrol grubu olarak ayarladım."""

df['group'] = df['ServerID'].map({1:'Test', 2:'Control', 3:'Control'})
df.drop(['ServerID','VisitPageFlagSum'],axis=1, inplace=True)

df.head()

df_control = df[df['group'] == 'Control'].copy()
df_control.reset_index(inplace=True, drop = True)

df_test = df[df['group'] == 'Test'].copy()
df_test.reset_index(inplace=True, drop = True)

df_control.head()

df_test.head()

"""Kontrol grubunun tanımlayıcı istatistiklerini inceleyelim."""

df_control.describe().T

df_test.describe().T

"""Kontrol veri setinde istediğimiz sayfaya girenlerin siteye girenlerin tamamına oranını hesaplayalım."""

control_sum_visit = df_control['VisitPageFlag'].count()
print("Sum visit for control group: ", control_sum_visit)
control_visit_1 = df_control[df_control['VisitPageFlag'] ==1]['VisitPageFlag'].count()
print("Visit Page target = 1 : ", control_visit_1)

control_ratio_visit = control_visit_1/control_sum_visit
control_ratio_visit

test_sum_visit = df_test['VisitPageFlag'].count()
print("Sum visit for test group: ", test_sum_visit)
test_visit_1 = df_test[df_test['VisitPageFlag'] ==1]['VisitPageFlag'].count()
print("Visit Page target = 1 : ", test_visit_1)

test_ratio_visit = test_visit_1/test_sum_visit
test_ratio_visit

"""Tıklanma oranlarına doğrudan baktığımızda iki grup arasında fark olduğunu görüyoruz. Test grubuna uygulanan yeni özelliğin daha fazla tıklama aldığı görülüyor. Fakat bu sonuç yanıltıcı olabilir. Bu nedenle istatistiksel olarak anlamlı bir fark var mı sorusuna cevap aramalıyız. Şimdi A/B testini gerçekleştireceğiz.


A/B testinin uygulanabilmesi için veri setinin Normallik ve Varyans homojenliği varsayımlarını karşılaması gerekir. Daha sonra hipotez testlerinin uygulanmasına geçilebilir.

Normallik ve varyans homojenliği sağlanıyorsa bağımsız iki örneklemli t testi (parametrik test) uygulanır.
Normallik ve varyansların homojenliği sağlanamıyorsa Mann-Whitney U testi (parametrik olmayan test) yapılır. Normallik varsayımı nasıl kontrol edilir? Bu konuda öncelikle H0 ve H1 hipotezlerini belirleyeceğiz.

H0 : Normallik varsayımı sağlanmıştır.

H1 : Normallik varsayımı sağlanmamıştır.

Şimdi normallik varsayımını kontrol edelim.

##Normality Assumption
"""

test_stat, pvalue = shapiro(df_control["VisitPageFlag"])
print('Test Stat = %.4f, p-value = %.4f' % (test_stat, pvalue))

test_stat, pvalue = shapiro(df_test["VisitPageFlag"])
print('Test Stat = %.4f, p-value = %.4f' % (test_stat, pvalue))

"""H0 reddedilir çünkü p değeri <0,05'tir. Normallik varsayımı sağlanmamıştır.

Bu nedenle Mann-Whitney U testini kullanacağız.

##Mann-Whitney U Test
"""

test_stat, pvalue = mannwhitneyu(df_control["VisitPageFlag"],
                                 df_test["VisitPageFlag"])
print('Test Stat = %.4f, p-value = %.4f' % (test_stat, pvalue))

"""H0 reddedildi çünkü p değeri<0,05. Yani istatistiksel olarak iki grup arasında fark olduğunu söyleyebiliriz."""

group_count = df.groupby(['group', 'VisitPageFlag'])['group'].count().reset_index(name='Count')
groupped = pd.crosstab(group_count['group'], group_count['VisitPageFlag'], values=group_count['Count'], aggfunc=np.sum, margins=True)

100*groupped.div(groupped['All'], axis=0)

"""Kontrol grubunda bağlantıya tıklama oranı %9,22 iken Test grubunda bu oran %11,55'e yükseldi. Yaptığımız testler sonucunda bu oran artışının tesadüf olmadığını, istatistiksel olarak kanıtlandığını söyleyebiliriz."""